"""remove_geolocation_add_light_sensors

Revision ID: cb9daef77144
Revises: 0002
Create Date: 2025-08-26 16:22:16.545235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb9daef77144'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mizu_sensor_hub', sa.Column('ambient_light', sa.Float(), nullable=True))
    op.add_column('mizu_sensor_hub', sa.Column('uv_light', sa.Float(), nullable=True))
    op.drop_column('mizu_sensor_hub', 'longitude')
    op.drop_column('mizu_sensor_hub', 'latitude')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mizu_sensor_hub', sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('mizu_sensor_hub', sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('mizu_sensor_hub', 'uv_light')
    op.drop_column('mizu_sensor_hub', 'ambient_light')
    # ### end Alembic commands ###
